### ISSUE TITLE
Obstacle pruning

### ISSUE THREAD

**Issue by luk3Sky** [Pera-Swarm/visualizer#36] opened 2021-01-23 22:29 UTC
I have encountered duplicate obstacles and virtual robot instances created on the Visualizer few times now. We need a way to remove duplicate objects.

**Comment by NuwanJ** [comment] 2021-01-24 04:07
I also see it. I tried, but no simple solution because of the async behavior of the JS. (Both localization and robot.create functions make robot instances at the same time). We need to implement some mutex lock or update the system with some initiation timeout.

**Comment by NuwanJ** [comment] 2021-01-28 11:39
It is now fixed by adding some delay interval. Please reopen it, if the issue is still there.

**Closed as completed by NuwanJ** 2021-01-28 11:39 UTC
Labels: enhancement
